/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description userId / password で認証し、JWT アクセストークンとリフレッシュトークンを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 認証失敗（詳細は返さない） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description レート制限超過（Retry-After ヘッダーで再試行可能秒数を通知） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guest-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ゲストログイン
         * @description パスワード不要でゲストユーザーとしてログインし、JWT トークンペアを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ゲストログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description ゲストユーザーが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * トークンリフレッシュ
         * @description リフレッシュトークンを消費し、新しいトークンペアを返す（Refresh Token Rotation）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description リフレッシュ成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description refreshToken が未指定 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description トークン無効または再利用検知 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description リフレッシュトークンを失効させる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description ログアウト成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** カテゴリ一覧取得 */
        get: {
            parameters: {
                query: {
                    balanceType: "0" | "1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description カテゴリ一覧（displayOrder 昇順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriesResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ダッシュボード集約データ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ダッシュボードデータ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支出一覧取得 */
        get: {
            parameters: {
                query?: {
                    period?: "week" | "month" | "lastMonth" | "all";
                    search?: string;
                    date?: string;
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支出一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 支出登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExpenseBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支出詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支出詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** 支出更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateExpenseBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 支出削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            result: "success";
                        };
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** テキストから支出情報をパース */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseParseRequest"];
                };
            };
            responses: {
                /** @description パース結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseParseResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予算一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 予算一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 予算登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBudgetBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予算詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 予算詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** 予算更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBudgetBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 予算削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            result: "success";
                        };
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** ユーザー登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** ユーザー更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** ユーザー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自己登録
         * @description メールアドレス不要の匿名登録。秘密の質問もあわせて設定する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["UserResponse"];
                        };
                    };
                };
                /** @description バリデーションエラー / ユーザーID重複 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register/check-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー名使用可能確認 */
        get: {
            parameters: {
                query: {
                    userId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 確認結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckUserNameResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/security-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 秘密の質問一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 質問一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SecurityQuestionListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** パスワードリカバリ: 秘密の質問取得 */
        get: {
            parameters: {
                query: {
                    userId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 質問取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryQuestionResponse"];
                    };
                };
                /** @description ユーザーが存在しないか質問未設定 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** パスワードリカバリ: 回答照合 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyRecoveryBody"];
                };
            };
            responses: {
                /** @description 照合成功。リセットトークンを返す（30分有効） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PasswordResetTokenResponse"];
                    };
                };
                /** @description 回答が不正 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ユーザーが存在しないか質問未設定 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description レート制限超過（Retry-After ヘッダーで再試行可能秒数を通知） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** パスワードリカバリ: パスワードリセット */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordBody"];
                };
            };
            responses: {
                /** @description パスワード更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description トークンが無効または期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description レート制限超過（Retry-After ヘッダーで再試行可能秒数を通知） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全取引データのエクスポート
         * @description ログイン中ユーザーの全取引データを JSON または CSV 形式でダウンロードする。
         */
        get: {
            parameters: {
                query?: {
                    format?: "json" | "csv";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description エクスポートデータ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                        "text/csv": unknown;
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー設定取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー設定（未設定時はデフォルト値を返す） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSettingsResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** ユーザー設定保存 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertUserSettingsBody"];
                };
            };
            responses: {
                /** @description 保存成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSettingsResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenPairResponse: {
            /** @enum {string} */
            result: "success";
            /** @example eyJhbGciOiJSUzI1NiJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJSUzI1NiJ9... */
            refreshToken: string;
            /** @example user01 */
            userId: string;
        };
        ErrorResponse: {
            /**
             * @example error
             * @enum {string}
             */
            result: "error";
            /** @example エラーメッセージ */
            message: string;
        };
        LoginRequest: {
            /** @example user01 */
            userId: string;
            /** @example •••••••• */
            password: string;
        };
        RefreshRequest: {
            /** @example eyJ... */
            refreshToken: string;
        };
        LogoutResponse: {
            /**
             * @example success
             * @enum {string}
             */
            result: "success" | "error";
            /** @example ログアウトしました */
            message: string;
        };
        LogoutRequest: {
            /** @example eyJ... */
            refreshToken?: string;
        };
        CategoryItem: {
            /**
             * @description カテゴリID
             * @example 1
             */
            id: number;
            /**
             * @description セマンティクキー
             * @example food
             */
            key: string;
            /**
             * @description 表示名
             * @example 食費
             */
            name: string;
            /**
             * @description アイコン/テキスト前景色
             * @example #f18840
             */
            color: string;
            /**
             * @description バッジ/ボタン背景色
             * @example #fef5ee
             */
            bg: string;
            /**
             * @description 収支タイプ（0=支出, 1=収入）
             * @example 0
             */
            balanceType: 0 | 1;
            /**
             * @description 表示順
             * @example 1
             */
            displayOrder: number;
        };
        CategoriesResponse: components["schemas"]["CategoryItem"][];
        ExpenseResponse: {
            /**
             * @description Expense ID (ULID)
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            id: string;
            /**
             * @description 金額（円）
             * @example 1000
             */
            amount: number;
            /**
             * @description 収支区分: 0=支出, 1=収入
             * @example 0
             */
            balanceType: 0 | 1;
            /**
             * @description ユーザーID
             * @example user01
             */
            userId: string;
            /**
             * @description カテゴリID
             * @example 1
             */
            categoryId: number;
            /**
             * @description 備考
             * @example 昼食代
             */
            content: string | null;
            /**
             * @description 日付 (YYYY-MM-DD)
             * @example 2024-03-15
             */
            date: string;
            /**
             * @description 作成日時 (ISO 8601)
             * @example 2024-03-15T12:00:00.000Z
             */
            createdDate: string;
            /**
             * @description 更新日時 (ISO 8601)
             * @example 2024-03-15T12:00:00.000Z
             */
            updatedDate: string;
            /**
             * @description 削除日時 (ISO 8601)
             * @example null
             */
            deletedDate: string | null;
        };
        DashboardResponse: {
            /**
             * @description 本日の支出合計（円）
             * @example 1500
             */
            todayExpense: number;
            /** @description 1日予算（設定未完了の場合 null） */
            dailyBudget: {
                /**
                 * @description 1日予算（円）
                 * @example 3000
                 */
                amount: number;
                /**
                 * @description 本日の残予算（円）
                 * @example 1500
                 */
                remaining: number;
                /**
                 * @description 残予算比率（0〜1+）
                 * @example 0.5
                 */
                ratio: number;
                /**
                 * @description 給料日まで何日
                 * @example 12
                 */
                daysUntilPayday: number;
            } | null;
            monthSummary: {
                /**
                 * @description 今月の支出合計
                 * @example 45000
                 */
                expense: number;
                /**
                 * @description 今月の収入合計
                 * @example 200000
                 */
                income: number;
            };
            /**
             * @description 先月の支出合計
             * @example 50000
             */
            lastMonthExpense: number;
            weeklyRecord: {
                /**
                 * @description 日付 (YYYY-MM-DD)
                 * @example 2026-06-13
                 */
                date: string;
                /**
                 * @description 曜日
                 * @example 金
                 */
                dow: string;
                /**
                 * @description 支出合計（円）
                 * @example 1500
                 */
                expense: number;
                /**
                 * @description 記録があるか
                 * @example true
                 */
                recorded: boolean;
            }[];
            recentExpenses: components["schemas"]["ExpenseResponse"][];
            /**
             * @description 連続記録日数
             * @example 5
             */
            streak: number;
            /**
             * @description 月間貯蓄目標（円）。未設定は 0
             * @example 30000
             */
            savingsGoal: number;
            /** @description 生活余力の算出入力（計算は @budget/common calculateLivingMargin） */
            livingMargin: {
                /**
                 * @description 総資産（円）。初回設定未完了の場合 null
                 * @example 960000
                 */
                totalAssets: number | null;
                /**
                 * @description 直近30日の実績日次平均支出（円/日）
                 * @example 8000
                 */
                avgDailyExpense: number;
                /**
                 * @description 月収（円/月）
                 * @example 250000
                 */
                monthlyIncome: number;
                /**
                 * @description 記録済み日数（ユニーク日付数）
                 * @example 30
                 */
                recordedDays: number;
            };
        };
        ExpenseListResponse: {
            expense: components["schemas"]["ExpenseResponse"][];
        };
        ExpenseDetailResponse: {
            expense: components["schemas"]["ExpenseResponse"];
        };
        CreateExpenseBody: {
            /** @description 支出データ */
            newData: {
                /**
                 * @description 金額（円）
                 * @example 1500
                 */
                amount: number;
                /**
                 * @description 収支区分: 0=支出, 1=収入
                 * @example 0
                 */
                balanceType: 0 | 1;
                /**
                 * @description ユーザーID
                 * @example user01
                 */
                userId: string;
                /**
                 * @description 日付 (YYYY-MM-DD)
                 * @example 2024-03-15
                 */
                date: string;
                /**
                 * @description カテゴリID（省略時はデフォルト: 1=食費）
                 * @example 3
                 */
                categoryId?: number;
                /**
                 * @description 備考
                 * @example 昼食代
                 */
                content?: string | null;
            };
        };
        UpdateExpenseBody: {
            /** @description 更新データ */
            updateData: {
                /**
                 * @description 金額（円）
                 * @example 1500
                 */
                amount: number;
                /**
                 * @description 収支区分: 0=支出, 1=収入
                 * @example 0
                 */
                balanceType: 0 | 1;
                /**
                 * @description 日付 (YYYY-MM-DD)
                 * @example 2024-03-15
                 */
                date: string;
                /**
                 * @description カテゴリID
                 * @example 3
                 */
                categoryId?: number;
                /**
                 * @description 備考
                 * @example 昼食代
                 */
                content?: string | null;
            };
        };
        ExpenseParseResponse: {
            /**
             * @description 抽出された金額（円）。見つからない場合は null
             * @example 900
             */
            amount: number | null;
            /**
             * @description 推定カテゴリ ID（0: 未分類）
             * @example 1
             */
            categoryId: number;
            /**
             * @description 入力テキスト（備考欄の初期値として利用）
             * @example ランチ代¥900
             */
            content: string;
            /**
             * @description パース実行日（YYYY-MM-DD）
             * @example 2026-05-09
             */
            date: string;
        };
        ExpenseParseRequest: {
            /**
             * @description パース対象テキスト（例: 「ランチ代¥900」「スーパーで1200円」）
             * @example ランチ代¥900
             */
            text: string;
            /** @description レシート画像（Base64）。現時点では未対応（将来的に AI モデルで処理） */
            imageBase64?: string;
        };
        BudgetResponse: {
            /**
             * @description Budget ID (ULID)
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            id: string;
            /**
             * @description 金額（円）
             * @example 1000
             */
            amount: number;
            /**
             * @description 収支区分: 0=支出, 1=収入
             * @example 0
             */
            balanceType: 0 | 1;
            /**
             * @description ユーザーID
             * @example user01
             */
            userId: string;
            /**
             * @description カテゴリID
             * @example 1
             */
            categoryId: number;
            /**
             * @description 備考
             * @example 食費予算
             */
            content: string | null;
            /**
             * @description 日付 (YYYY-MM)
             * @example 2024-03
             */
            date: string;
            /** @description 作成日時 (ISO 8601) */
            createdDate: string;
            /** @description 更新日時 (ISO 8601) */
            updatedDate: string;
            /**
             * @description 削除日時 (ISO 8601)
             * @example null
             */
            deletedDate: string | null;
        };
        BudgetListResponse: {
            budget: components["schemas"]["BudgetResponse"][];
        };
        BudgetDetailResponse: {
            budget: components["schemas"]["BudgetResponse"];
        };
        CreateBudgetBody: {
            /** @description 予算データ */
            newData: {
                [key: string]: unknown;
            };
        };
        UserResponse: {
            /**
             * @description ユーザーID
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            userId: string;
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName: string;
            /**
             * @description メールアドレス
             * @example taro@example.com
             */
            email: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role: "ADMIN" | "USER" | "GUEST";
            /**
             * @description ユーザーステータス
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description 作成日時 (ISO 8601)
             * @example 2026-04-13T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 更新日時 (ISO 8601)
             * @example 2026-04-13T00:00:00.000Z
             */
            updatedAt: string;
        };
        UserListResponse: {
            user: components["schemas"]["UserResponse"][];
        };
        UserDetailResponse: {
            user: components["schemas"]["UserResponse"];
        };
        CreateUserBody: {
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName: string;
            /** @description パスワード（平文） */
            password: string;
            /**
             * Format: email
             * @description メールアドレス
             * @example taro@example.com
             */
            email?: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER" | "GUEST";
        };
        UpdateUserBody: {
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName?: string;
            /** @description 新しいパスワード（平文）。省略時は変更なし */
            password?: string;
            /**
             * Format: email
             * @description メールアドレス
             * @example taro@example.com
             */
            email?: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER" | "GUEST";
            /**
             * @description ユーザーステータス
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        SuccessResponse: {
            /**
             * @example success
             * @enum {string}
             */
            result: "success";
        };
        RegisterBody: {
            /**
             * @description ログインIDを兼ねるユーザー名
             * @example yamada_taro
             */
            userId: string;
            /**
             * @description 表示名（省略時はuserIdと同値）
             * @example 山田太郎
             */
            displayName?: string;
            /** @description パスワード（平文） */
            password: string;
            /**
             * @description 秘密の質問ID
             * @example 1
             */
            securityQuestionId: number;
            /**
             * @description 秘密の質問の回答（平文）
             * @example ○○市
             */
            securityAnswer: string;
        };
        CheckUserNameResponse: {
            /**
             * @description 使用可能かどうか
             * @example true
             */
            available: boolean;
        };
        SecurityQuestion: {
            /**
             * @description 質問ID
             * @example 1
             */
            id: number;
            /**
             * @description 質問文
             * @example 幼少期に住んでいた町・村の名前は？
             */
            text: string;
        };
        SecurityQuestionListResponse: {
            questions: components["schemas"]["SecurityQuestion"][];
        };
        RecoveryQuestionResponse: {
            /**
             * @description 質問ID
             * @example 1
             */
            questionId: number;
            /**
             * @description 質問文
             * @example 幼少期に住んでいた町・村の名前は？
             */
            questionText: string;
        };
        PasswordResetTokenResponse: {
            /** @enum {string} */
            result: "success";
            /** @description パスワードリセット用一時トークン（30分有効） */
            resetToken: string;
            /** @description 有効期限 (ISO 8601) */
            expiresAt: string;
        };
        VerifyRecoveryBody: {
            /**
             * @description ユーザーID
             * @example yamada_taro
             */
            userId: string;
            /** @description 秘密の質問の回答 */
            answer: string;
        };
        ResetPasswordBody: {
            /** @description パスワードリセット用一時トークン */
            resetToken: string;
            /** @description 新しいパスワード（平文） */
            newPassword: string;
        };
        /** @description 固定費内訳（null = 未設定） */
        FixedExpensesDetail: {
            /**
             * @description 家賃（円）
             * @example 80000
             */
            rent: number;
            /**
             * @description 光熱費（円）
             * @example 15000
             */
            utilities: number;
            /**
             * @description 保険（円）
             * @example 10000
             */
            insurance: number;
            /**
             * @description サブスク（円）
             * @example 5000
             */
            subscriptions: number;
            /**
             * @description 交通費（円）
             * @example 10000
             */
            transportation: number;
            /**
             * @description その他（円）
             * @example 5000
             */
            other: number;
        } | null;
        UserSettingsResponse: {
            /**
             * @description 総資産（円）
             * @example 5000000
             */
            totalAssets: number;
            /**
             * @description 月次固定収入（円）
             * @example 200000
             */
            monthlyIncome: number;
            /**
             * @description 給料日（月の何日か: 1〜31）
             * @example 25
             */
            paydayDay: number;
            /**
             * @description 月次固定費合計（円）
             * @example 80000
             */
            fixedExpenses: number;
            fixedExpensesDetail: components["schemas"]["FixedExpensesDetail"];
            /**
             * @description 月間貯蓄目標（円）。1日予算の算出時に控除する
             * @example 30000
             */
            savingsGoal: number;
            /**
             * @description 初回設定完了フラグ
             * @example false
             */
            initialSetupCompleted: boolean;
        };
        UpsertUserSettingsBody: {
            /**
             * @description 総資産（円）
             * @example 5000000
             */
            totalAssets: number;
            /**
             * @description 月次固定収入（円）
             * @example 200000
             */
            monthlyIncome: number;
            /**
             * @description 給料日（月の何日か: 1〜31）
             * @example 25
             */
            paydayDay: number;
            /**
             * @description 月次固定費合計（円）— fixedExpensesDetail がある場合は無視
             * @example 80000
             */
            fixedExpenses: number;
            fixedExpensesDetail?: components["schemas"]["FixedExpensesDetail"] & unknown;
            /**
             * @description 月間貯蓄目標（円）。省略時は既存値を維持
             * @example 30000
             */
            savingsGoal?: number;
            /**
             * @description 初回設定完了フラグ
             * @example true
             */
            initialSetupCompleted?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
